import dayjs from "dayjs";
import { IQuickLink } from "../components/QuickLink";
import { Transaction } from "../redux/transactionSlice";

export const defaultCategories = [
  {
    id: 1,
    name: "Food & Drinks",
    icon: "restaurant",
    color: "#EF4444",
  },
  {
    id: 2,
    name: "Housing",
    icon: "home",
    color: "#EAB308",
  },
  {
    id: 3,
    name: "Shopping",
    icon: "bag",
    color: "#F97316",
  },
  {
    id: 4,
    name: "Family",
    icon: "people",
    color: "#22C55E",
  },
  {
    id: 5,
    name: "Transportation",
    icon: "car",
    color: "#3B82F6",
  },
  {
    id: 6,
    name: "Travel/ Vacation",
    icon: "airplane",
    color: "#8B5CF6",
  },
  {
    id: 7,
    name: "Entertainment",
    icon: "game-controller",
    color: "#1F2937",
  },
  {
    id: 8,
    name: "Health",
    icon: "medical",
    color: "#EF4444",
  },
];

export const defaultTransactions: Transaction[] = [
  {
    id: 1,
    category: "Food & Drinks",
    amount: 4200,
    date: dayjs().format("ddd, D MMM"),
    color: "#EF4444",
    icon: "restaurant",
    note: "Lunch at Chick’n Lick’n",
    imageUrl: "https://via.placeholder.com/100",
  },
  {
    id: 2,
    category: "Family",
    amount: 18000,
    date: dayjs().format("ddd, D MMM"),
    color: "#22C55E",
    icon: "people",
    note: "Children's school supplies",
    imageUrl: "https://via.placeholder.com/100",
  },
  {
    id: 3,
    category: "Transportation",
    amount: 1000,
    date: dayjs().format("ddd, D MMM"),
    color: "#3B82F6",
    icon: "car",
    note: "Bus fare to office",
    imageUrl: "https://via.placeholder.com/100",
  },
  {
    id: 4,
    category: "Entertainment",
    amount: 3500,
    date: dayjs().format("ddd, D MMM"),
    color: "#1F2937",
    icon: "game-controller",
    note: "Netflix subscription",
    imageUrl: "https://via.placeholder.com/100",
  },
  {
    id: 5,
    category: "Food & Drinks",
    amount: 2500,
    date: dayjs().subtract(1, "day").format("ddd, D MMM"),
    color: "#EF4444",
    icon: "restaurant",
    note: "Shawarma & Drink",
    imageUrl: "https://via.placeholder.com/100",
  },
  {
    id: 6,
    category: "Family",
    amount: 6000,
    date: dayjs().subtract(1, "day").format("ddd, D MMM"),
    color: "#22C55E",
    icon: "people",
    note: "Grocery shopping for home",
    imageUrl: "https://via.placeholder.com/100",
  },
  {
    id: 7,
    category: "Transportation",
    amount: 1500,
    date: dayjs().subtract(1, "day").format("ddd, D MMM"),
    color: "#3B82F6",
    icon: "car",
    note: "Bolt to market",
    imageUrl: "https://via.placeholder.com/100",
  },
  {
    id: 8,
    category: "Entertainment",
    amount: 8000,
    date: dayjs().subtract(1, "day").format("ddd, D MMM"),
    color: "#1F2937",
    icon: "game-controller",
    note: "Cinema outing",
    imageUrl: "https://via.placeholder.com/100",
  },
  {
    id: 9,
    category: "Food & Drinks",
    amount: 3000,
    date: dayjs().subtract(2, "day").format("ddd, D MMM"),
    color: "#EF4444",
    icon: "restaurant",
    note: "Dinner at Burger King",
    imageUrl: "https://via.placeholder.com/100",
  },
  {
    id: 10,
    category: "Family",
    amount: 12000,
    date: dayjs().subtract(2, "day").format("ddd, D MMM"),
    color: "#22C55E",
    icon: "people",
    note: "Gift for Mum",
    imageUrl: "https://via.placeholder.com/100",
  },
  {
    id: 11,
    category: "Transportation",
    amount: 2000,
    date: dayjs().subtract(2, "day").format("ddd, D MMM"),
    color: "#3B82F6",
    icon: "car",
    note: "Fuel refill",
    imageUrl: "https://via.placeholder.com/100",
  },
  {
    id: 12,
    category: "Entertainment",
    amount: 5000,
    date: dayjs().subtract(2, "day").format("ddd, D MMM"),
    color: "#1F2937",
    icon: "game-controller",
    note: "PS5 gaming night",
    imageUrl: "https://via.placeholder.com/100",
  },
];

export const quickLinks: IQuickLink[] = [
  {
    title: "Add Expense",
    icon: require("@/assets/images/wallet-add.png"),
    linkTo: "/(tabs)/expenses",
  },
  {
    title: "Create a Category",
    icon: require("@/assets/images/category-2.png"),
    linkTo: undefined,
  },
];
